version: '3.4'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:${PG_VERSION:-latest}
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_DB: ${API_DB_NAME}
        POSTGRES_USER: ${API_DB_USR_NAME}
        POSTGRES_PASSWORD: ${API_DB_PASSWD}
    ports:
      - ${API_DB_PORT}:${API_DB_PORT}

  graph-ql:
    image: ${OWNER_NAME}/${APP_NAME}:${DEPLOY_VERSION:-latest}
    container_name: ${CONTAINER_NAME}
    env_file:
    - .env
    environment:
      NODE_ENV: production
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${API_HOST_PORT}:${API_CONTAINER_PORT}
    depends_on:
      postgres:
        condition: service_started